name: Deploy to Production

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run comprehensive test suite
      run: npm run test:production
      env:
        NODE_ENV: test
    
    - name: Run security audit
      run: npm audit --audit-level high || echo "⚠️  Security audit found issues but continuing deployment"
      continue-on-error: true
    
    - name: Check bundle size
      run: npm run build
      env:
        NODE_ENV: production

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel (Production)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PROD }}
        working-directory: ./
        scope: ${{ secrets.VERCEL_ORG_ID }}
        vercel-args: '--prod'
    
    - name: Run Production Smoke Tests
      run: |
        sleep 60  # Wait for deployment
        npm run test:smoke-prod
      env:
        PROD_URL: https://braindump.com
    
    - name: Notify deployment success
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: '🚀 BrainDump Production Deployment Successful!'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
